AllCops:
  TargetRubyVersion: 2.1
Lint/HandleExceptions:
  Exclude:
  - 'spec/spec_helper.rb'
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  Exclude:
  - 'lib/db_text_search/case_insensitive/abstract_adapter.rb'
  - 'lib/db_text_search/full_text/abstract_adapter.rb'
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/MethodLength:
  Max: 16
Metrics/ModuleLength:
  Max: 130
  Exclude:
  - 'spec/**/*.rb'
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'
Layout/AlignParameters:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/IndentHash:
  IndentationWidth: 4
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/FirstParameterIndentation:
  IndentationWidth: 4
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4
Layout/SpaceAroundOperators:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/UnneededPercentQ:
  Enabled: false
Metrics/LineLength:
  Max: 120
